#!/usr/bin/env bash

# Remove Fedora's flatpak repo, if it exists
if grep -qz 'fedora' <<< "$(flatpak remotes)"; then
  flatpak remote-delete --user fedora --force
  flatpak remote-delete --user fedora-testing --force
fi

REPO_INFO="/usr/share/bluebuild/default-flatpaks/user/repo-info.yml"
REPO_URL=$(yq '.repo-url' $REPO_INFO)
REPO_NAME=$(yq '.repo-name' $REPO_INFO)
REPO_TITLE=$(yq '.repo-title' $REPO_INFO)

# Set up per-user Flatpak repository
if [[ ! $REPO_URL == "null" && ! $REPO_NAME == "null" ]]; then
  flatpak remote-add --if-not-exists --user "$REPO_NAME" "$REPO_URL"
  echo "Adding remote $REPO_NAME from $REPO_URL"  
fi

# Change repository title to configured title, if not null
if [[ ! $REPO_TITLE == "null" ]]; then
  flatpak remote-modify --user "$REPO_NAME" --title="$REPO_TITLE"
  echo "Setting title $REPO_TITLE for remote $REPO_NAME"  
fi

# Notifications config
NOTIFICATIONS_FILE="/usr/share/bluebuild/default-flatpaks/notifications"
USER_NOTIFICATIONS_FILE="/etc/bluebuild/default-flatpaks/notifications"
# Ignore words starting with # symbol, whitelines & duplicate entries for notifications config
MAINTAINER_NOTIFICATIONS=$(cat "$NOTIFICATIONS_FILE" | grep -v -E '^#|^$' | awk '!seen[$0]++')
USER_NOTIFICATIONS=$(cat "$USER_NOTIFICATIONS_FILE" | grep -v -E '^#|^$' | awk '!seen[$0]++')

# If user modified notifications config, utilize user's configuration, otherwise maintainer's
if [[ -n $USER_NOTIFICATIONS ]]; then
  NOTIFICATIONS="$USER_NOTIFICATIONS"
else
  NOTIFICATIONS="$MAINTAINER_NOTIFICATIONS"
fi  

# Installed flatpaks
FLATPAK_LIST=$(flatpak list --user --columns=application)

# Flatpak list files
INSTALL_LIST_FILE="/usr/share/bluebuild/default-flatpaks/user/install"
REMOVE_LIST_FILE="/usr/share/bluebuild/default-flatpaks/user/remove"
USER_INSTALL_LIST_FILE="/etc/bluebuild/default-flatpaks/user/install"
USER_REMOVE_LIST_FILE="/etc/bluebuild/default-flatpaks/user/remove"
# Ignore words starting with # symbol, whitelines & duplicate entries for flatpak list files.
COMBINED_INSTALL_PRELIST=$(cat "$INSTALL_LIST_FILE" "$USER_INSTALL_LIST_FILE" | grep -v -E '^#|^$' | awk '!seen[$0]++')
COMBINED_REMOVE_PRELIST=$(cat "$REMOVE_LIST_FILE" "$USER_REMOVE_LIST_FILE" | grep -v -E '^#|^$' | awk '!seen[$0]++')
# Avoid install/remove loop scenario when you have duplicate entry in install & remove list at the same time
# (from user's side, as maintainer's-side will be handled by the module itself in the future)
# cat doesn't work, because this is not a file
COMBINED_INSTALL_LIST=$(sort -u <(cat "$COMBINED_INSTALL_PRELIST" "$USER_REMOVE_LIST_FILE")) #(exclude duplicates from "$USER_REMOVE_LIST_FILE")
COMBINED_REMOVE_LIST=$(sort -u <(cat "$COMBINED_REMOVE_PRELIST" "$USER_INSTALL_LIST_FILE")) #(exclude duplicates from "$USER_INSTALL_LIST_FILE")

# Install flatpaks in list
if [[ -f $INSTALL_LIST_FILE ]] || [[ -f $USER_INSTALL_LIST_FILE ]]; then
  if [[ -n $FLATPAK_LIST ]]; then
    INSTALL_LIST=$(comm -23 <(echo "$COMBINED_INSTALL_LIST" | sort) <(echo "$FLATPAK_LIST" | sort))
  else
    INSTALL_LIST="$COMBINED_INSTALL_LIST"
  fi
  if [[ -n $INSTALL_LIST ]] && [[ ! $NOTIFICATIONS == "true" ]]; then
    flatpak install --user --noninteractive "$REPO_NAME" ${INSTALL_LIST[@]}
  elif  [[ -n $INSTALL_LIST ]] && [[ $NOTIFICATIONS == "true" ]]; then
    notify-send "Flatpak Installer" "Started install of user flatpaks" --app-name="Flatpak Installer" -u NORMAL
    flatpak install --user --noninteractive "$REPO_NAME" ${INSTALL_LIST[@]}  
    notify-send "Flatpak Installer" "Finished install of user flatpaks:\n$INSTALL_LIST" --app-name="Flatpak Installer" -u NORMAL
  fi
fi

# Remove flatpaks in list
if [[ -f $REMOVE_LIST_FILE ]] || [[ -f $USER_REMOVE_LIST_FILE ]]; then
  REMOVE_LIST=$(comm -12 <(echo "$COMBINED_REMOVE_LIST" | sort) <(echo "$FLATPAK_LIST" | sort))
  if [[ -n $REMOVE_LIST ]] && [[ ! $NOTIFICATIONS == "true" ]]; then
    flatpak uninstall --user --noninteractive ${REMOVE_LIST[@]}
  elif [[ -n $REMOVE_LIST ]] && [[ $NOTIFICATIONS == "true" ]]; then
    notify-send "Flatpak Installer" "Started uninstall of some user flatpaks" --app-name="Flatpak Installer" -u NORMAL  
    flatpak uninstall --user --noninteractive ${REMOVE_LIST[@]}  
    notify-send "Flatpak Installer" "Finished uninstall of user flatpaks:\n$REMOVE_LIST" --app-name="Flatpak Installer" -u NORMAL
  fi  
fi
