#!/usr/bin/env bash

# Remove Fedora's flatpak repo, if it exists
if grep -qz 'fedora' <<< "$(flatpak remotes)"; then
  flatpak remote-delete --user fedora --force
  flatpak remote-delete --user fedora-testing --force
fi

REPO_INFO="/etc/flatpak/user/repo-info.yml"
REPO_URL=$(yq '.repo-url' $REPO_INFO)
REPO_NAME=$(yq '.repo-name' $REPO_INFO)
REPO_TITLE=$(yq '.repo-title' $REPO_INFO)

# Set up per-user Flatpak repository
if [[ ! $REPO_URL == "null" && ! $REPO_NAME == "null" ]]; then
  flatpak remote-add --if-not-exists --user "$REPO_NAME" "$REPO_URL"
  echo "Adding remote $REPO_NAME from $REPO_URL"  
fi

# Change repository title to configured title, if not null
if [[ ! $REPO_TITLE == "null" ]]; then
  flatpak remote-modify --user "$REPO_NAME" --title="$REPO_TITLE"
  echo "Setting title $REPO_TITLE for remote $REPO_NAME"  
fi

# Notifications config
NOTIFICATIONS=$(cat /etc/flatpak/notifications)

# Installed flatpaks
FLATPAK_LIST=$(flatpak list --user --columns=application)

# Flatpak list files
INSTALL_LIST_FILE="/etc/flatpak/user/install"
REMOVE_LIST_FILE="/etc/flatpak/user/remove"

# Install flatpaks in list
if [[ -f $INSTALL_LIST_FILE ]]; then
  if [[ -n $FLATPAK_LIST ]]; then
    INSTALL_LIST=$(echo "$FLATPAK_LIST" | grep -vf - "$INSTALL_LIST_FILE")
  else
    INSTALL_LIST=$(cat $INSTALL_LIST_FILE)
  fi
  if [[ -n $INSTALL_LIST ]] && [[ ! $NOTIFICATIONS == "true" ]]; then
    flatpak install --user --noninteractive "$REPO_NAME" ${INSTALL_LIST[@]}
  elif  [[ -n $INSTALL_LIST ]] && [[ $NOTIFICATIONS == "true" ]]; then
    notify-send "Flatpak Installer" "Started install of user flatpaks" --app-name="Flatpak Installer" -u NORMAL
    flatpak install --user --noninteractive "$REPO_NAME" ${INSTALL_LIST[@]}  
    notify-send "Flatpak Installer" "Finished install of user flatpaks:\n$INSTALL_LIST" --app-name="Flatpak Installer" -u NORMAL
  fi
fi

# Remove flatpaks in list
if [[ -f $REMOVE_LIST_FILE ]]; then
  REMOVE_LIST=$(echo "$FLATPAK_LIST" | grep -o -f - "$REMOVE_LIST_FILE")
  if [[ -n $REMOVE_LIST ]] && [[ ! $NOTIFICATIONS == "true" ]]; then
    flatpak uninstall --user --noninteractive ${REMOVE_LIST[@]}
  elif [[ -n $REMOVE_LIST ]] && [[ $NOTIFICATIONS == "true" ]]; then
    notify-send "Flatpak Installer" "Started uninstall of some user flatpaks" --app-name="Flatpak Installer" -u NORMAL  
    flatpak uninstall --user --noninteractive ${REMOVE_LIST[@]}  
    notify-send "Flatpak Installer" "Finished uninstall of user flatpaks:\n$REMOVE_LIST" --app-name="Flatpak Installer" -u NORMAL
  fi  
fi
